import type { SkinConfig, Achievement } from '../types/game';

export const SKINS: SkinConfig[] = [
  {
    id: 'classic',
    name: 'Classic Green',
    cost: 0,
    description: 'The legendary explorer. Simple and green.',
    colorHead: '#10b981',
    colorBody: '#059669',
    glowColor: 'rgba(16, 185, 129, 0.4)',
    pattern: 'classic',
  },
  {
    id: 'king_cobra',
    name: 'King Cobra',
    cost: 150,
    description: 'Golden yellow scales with a warning pattern.',
    colorHead: '#fbbf24',
    colorBody: '#d97706',
    glowColor: 'rgba(251, 191, 36, 0.4)',
    pattern: 'stripes',
  },
  {
    id: 'python',
    name: 'Jungle Python',
    cost: 300,
    description: 'Camouflage print optimized for jungle environments.',
    colorHead: '#854d0e',
    colorBody: '#3f6212',
    glowColor: 'rgba(63, 98, 18, 0.4)',
    pattern: 'stripes',
  },
  {
    id: 'dragon_snake',
    name: 'Dragon Snake',
    cost: 500,
    description: 'Spiked head and deep crimson dragon scales.',
    colorHead: '#ef4444',
    colorBody: '#991b1b',
    glowColor: 'rgba(239, 68, 68, 0.5)',
    pattern: 'dragon',
  },
  {
    id: 'ice_snake',
    name: 'Frost Wyrm',
    cost: 700,
    description: 'Formed from deep ice. Emits a cold frost aura.',
    colorHead: '#67e8f9',
    colorBody: '#0891b2',
    glowColor: 'rgba(6, 182, 212, 0.6)',
    pattern: 'ice',
  },
  {
    id: 'fire_snake',
    name: 'Hellfire Serpent',
    cost: 800,
    description: 'Born in active volcanoes. Shines with molten lava.',
    colorHead: '#f97316',
    colorBody: '#c2410c',
    glowColor: 'rgba(249, 115, 22, 0.6)',
    pattern: 'fire',
  },
  {
    id: 'galaxy_snake',
    name: 'Nebula Stalker',
    cost: 1000,
    description: 'Translucent cosmic texture filled with stardust.',
    colorHead: '#a855f7',
    colorBody: '#581c87',
    glowColor: 'rgba(168, 85, 247, 0.6)',
    pattern: 'galaxy',
  },
  {
    id: 'golden_snake',
    name: 'Midas Snake',
    cost: 1200,
    description: 'Forged from pure, polished solid gold.',
    colorHead: '#f59e0b',
    colorBody: '#fbbf24',
    glowColor: 'rgba(245, 158, 11, 0.7)',
    pattern: 'metallic',
  },
  {
    id: 'shadow_snake',
    name: 'Void Shadow',
    cost: 1500,
    description: 'Infused with void energy. Leaves a shadowy trail.',
    colorHead: '#1e1b4b',
    colorBody: '#030712',
    glowColor: 'rgba(30, 27, 75, 0.8)',
    pattern: 'shadow',
  },
];

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_step',
    title: 'First Step',
    description: 'Complete Level 1',
    reward: 50,
    check: (state) => {
      return state.unlockedLevel > 1;
    },
  },
  {
    id: 'fruit_chaser',
    title: 'Fruit Chaser',
    description: 'Eat 50 fruits in total',
    reward: 100,
    check: (_, totalFruits) => totalFruits >= 50,
  },
  {
    id: 'fruit_slayer',
    title: 'Fruit Master',
    description: 'Eat 200 fruits in total',
    reward: 300,
    check: (_, totalFruits) => totalFruits >= 200,
  },
  {
    id: 'level_10',
    title: 'Crystal Cleanser',
    description: 'Complete Level 10',
    reward: 200,
    check: (state) => state.unlockedLevel > 10,
  },
  {
    id: 'level_25',
    title: 'Jungle King',
    description: 'Complete Level 25',
    reward: 400,
    check: (state) => state.unlockedLevel > 25,
  },
  {
    id: 'level_50',
    title: 'Absolute Ruler',
    description: 'Complete all 50 levels!',
    reward: 1000,
    check: (state) => {
      // UnlockedLevel would be 51 if level 50 is completed
      return state.unlockedLevel > 50;
    },
  },
  {
    id: 'collector',
    title: 'Skin Collector',
    description: 'Unlock 3 skins from the shop',
    reward: 150,
    check: (state) => state.unlockedSkins.length >= 3,
  },
  {
    id: 'hoarder',
    title: 'Rich Explorer',
    description: 'Earn 1000 total coins',
    reward: 200,
    check: (state) => state.coins >= 1000,
  },
];
export default { SKINS, ACHIEVEMENTS };
